services:
  # ----------------------- DATABASE -----------------------
  db:
    image: postgres:15
    container_name: ev_db
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: evcharging
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ev_net

  # ----------------------- KAFKA -----------------------
  
  # ----------------------- CENTRAL -----------------------
  central:
    build: ./central/backend
    container_name: ev_central
    restart: always
    depends_on:
      - db
#      - kafka
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: evcharging
      DB_USER: usuario
      DB_PASSWORD: contraseña
      KAFKA_BOOTSTRAP: kafka:9092
      CENTRAL_PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./central:/app/backend
    networks:
      - ev_net
    command: python EV_Central.py

  # ----------------------- NODE FRONTEND -----------------------
  front:
    build: ./central/frontend
    container_name: frontend
    depends_on:
      - db
      - central
    ports:
      - "3000:3000"
    volumes:
      - ./front:/usr/src/app
    networks:
      - ev_net
    command: npm run start
  # ----------------------- CHARGING POINTS -----------------------

  # ----------------------- VOLUMES & NETWORKS -----------------------
volumes:
  postgres_data:

networks:
  ev_net:
    driver: bridge