version: "3.8"

services:
  # ----------------------- DATABASE -----------------------
  db:
    image: postgres:15
    container_name: ev_db
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: evcharging
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ev_net

  # ----------------------- KAFKA -----------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: ev_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ev_net

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: ev_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    networks:
      - ev_net

  # ----------------------- CENTRAL -----------------------
  #central:
  #  build: ./central/backend
  #  container_name: ev_central
  #  restart: always
  #  depends_on:
  #    - db
  #    - kafka
  #  environment:
  #    DB_HOST: db
  #    DB_PORT: 5432
  #    DB_NAME: evcharging
  #    DB_USER: usuario
  #    DB_PASSWORD: contraseña
  #    KAFKA_BOOTSTRAP: kafka:9092
  #    CENTRAL_PORT: 8000
  #  ports:
  #    - "8000:8000"
  #  volumes:
  #    - ./central/backend:/app
  #  networks:
  #    - ev_net
  #  command: python EV_Central.py

  # Dummy central
  central:
    build: ./charging_point
    container_name: ev_central
    restart: always
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      CENTRAL_PORT: 9000
    ports:
      - "9000:9000"
    volumes:
      - ./charging_point:/app
    networks:
      - ev_net
    command: python dummy_central.py


  # ----------------------- CHARGING POINTS -----------------------
  cp_engine:
    build: ./charging_point
    container_name: ev_cp_engine
    command: python EV_CP_E.py
    environment:
      - ENGINE_PORT=7000
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    networks:
      - ev_net

  cp_monitor:
    build: ./charging_point
    container_name: ev_cp_monitor
    command: python EV_CP_M.py
    environment:
      - ENGINE_HOST=ev_cp_engine
      - ENGINE_PORT=7000
      - CENTRAL_HOST=ev_central
      - CENTRAL_PORT=8000
      - KAFKA_BROKER=kafka:9092
      - UUID_PATH=/app/cp_uuid.json
    depends_on:
      - cp_engine
      - central
    networks:
      - ev_net

  # ----------------------- DRIVERS -----------------------
  driver1:
    build: ./driver
    container_name: ev_driver1
    restart: always
    depends_on:
      - kafka
      - central
    environment:
      DRIVER_ID: Driver1
      KAFKA_BOOTSTRAP: kafka:9092
    volumes:
      - ./driver:/app
    networks:
      - ev_net
    command: python EV_Driver.py

  driver2:
    build: ./driver
    container_name: ev_driver2
    restart: always
    depends_on:
      - kafka
      - central
    environment:
      DRIVER_ID: Driver2
      KAFKA_BOOTSTRAP: kafka:9092
    volumes:
      - ./driver:/app
    networks:
      - ev_net
    command: python EV_Driver.py

# ----------------------- VOLUMES & NETWORKS -----------------------
volumes:
  postgres_data:

networks:
  ev_net:
    driver: bridge
