services:
  # ----------------------- DATABASE -----------------------
  db:
    image: postgres:15
    container_name: ev_db
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: evcharging
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ev_net
  # ----------------------- CENTRAL -----------------------
  central:
    build: ./central
    container_name: central
    environment:
      DB_HOST: "db"
      DB_PORT: 5432
      DB_NAME: "evcharging"
      DB_USER: "usuario"
      DB_PASSWORD: "contraseña"
      KAFKA_BOOTSTRAP: "kafka:9092"
      # kafka
      CENTRAL_DRIVER_COMMANDS: "Central.Driver.Commands"
      CENTRAL_CP_COMMANDS: "Central.CP.Commands"
      DRIVER_COMMANDS: "Driver.Commands" 
      # sockets
      CP_CENTRAL_STATUS_SOCKET: "CP_Central_Status_Socket"
      CP_CENTRAL_CREATE_SOCKET: "CP_Central_Create_Socket"
      VIEW_CENTRAL_CMD_SOCKET: "View_Central_CMD_Socket"
      # TIMEOUT
      TIMEOUTMS: 6000
      
    depends_on:
      kafka:
        condition: service_healthy
      db: 
        condition: service_started
    ports:
      - "4000:4000"
    networks:
      - ev_net
    command: npm run start
  # ----------------------- CENTRAL 2 -----------------------
  
  ev_central:
    build: ./sv-central
    container_name: ev_central
    environment:
      DB_HOST: "db"
      DB_PORT: 5432
      DB_NAME: "evcharging"
      DB_USER: "usuario"
      DB_PASSWORD: "contraseña"
      KAFKA_BOOTSTRAP: "kafka:9092"
      # kafka
      CENTRAL_DRIVER_COMMANDS: "Central.Driver.Commands"
      CENTRAL_CP_COMMANDS: "Central.CP.Commands"
      DRIVER_COMMANDS: "Driver.Commands"

      PORT: 4000
    depends_on:
      #kafka:
      #  condition: service_healthy
      db: 
        condition: service_started
    ports:
      - "4000:4000"
    networks:
      - ev_net
    command: npm run start:prod

  ev_registry:
    build: ./ev_registry
    container_name: ev_registry
    environment:
      DB_HOST: "db"
      DB_PORT: 5432
      DB_NAME: "evcharging"
      DB_USER: "usuario"
      DB_PASSWORD: "contraseña"
      PORT: 4001

    volumes:
      - ./certs/registry.crt:/certs/registry.crt
      - ./certs/registry.key:/certs/registry.key
    depends_on:
      db: 
        condition: service_started
    ports:
      - "4001:4001"
    networks:
      - ev_net
    command: npm run start:prod

  # ----------------------- KAFKA -----------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: ev_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ev_net

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: ev_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 10s
      timeout: 5s
      retries: 10

    ports:
      - "9092:9092"
    networks:
      - ev_net
  # ----------------------- CHARGING POINTS -----------------------
  cp_pair:
    build:
      context: ./charging_point/cp
      dockerfile: Dockerfile
    environment:
      KAFKA_BROKER: "kafka:9092"
      CENTRAL_HOST: "http://central:4000"
      ENGINE_PORT: "7000"
      ENGINE_HOST: "0.0.0.0"
      MONITOR_PORT: "9000"
      CP_INDEX: "${HOSTNAME}"
    depends_on:
      kafka:
        condition: service_healthy
      central:
        condition: service_started
    ports:
      - "9100-9199:9000"
    networks: [ev_net]
    restart: on-failure

  # ----------------------- DRIVERS -----------------------
  driver:
    build:
      context: ./driver
      dockerfile: Dockerfile
    environment:
      KAFKA_BOOTSTRAP: "kafka:9092"
      FLASK_PORT: "5000"
    depends_on:
      kafka:
        condition: service_healthy
      central:
        condition: service_started
    # UI del driver expuesta por réplica en rango 9200-9299
    ports:
      - "9200-9299:5000"
    networks: [ev_net]
    restart: on-failure

  # ----------------------- VOLUMES & NETWORKS -----------------------
volumes:
  postgres_data:
  
  kafka_data:

networks:
  ev_net:
    driver: bridge