services:
  # ----------------------- DATABASE -----------------------
  db:
    image: postgres:15
    container_name: ev_db
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: evcharging
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ev_net
  # ----------------------- CENTRAL -----------------------
  
  ev_central:
    build: ./sv-central
    container_name: ev_central
    environment:
      DB_HOST: "db"
      DB_PORT: 5432
      DB_NAME: "evcharging"
      DB_USER: "usuario"
      DB_PASSWORD: "contraseña"
      # kafka

      KAFKA_BROKER: "kafka:9092"
      KAFKA_GROUPID: "commands-service"
      
      CENTRAL_DRIVER_COMMANDS: "Central.Driver.Commands"
      CENTRAL_CP_COMMANDS: "Central.CP.Commands"
      DRIVER_COMMANDS: "Driver.Commands"

      PORT: 4000
    volumes:
      - ./certs/central.crt:/certs/central.crt
      - ./certs/central.key:/certs/central.key
    depends_on:
      kafka:
        condition: service_healthy
      db: 
        condition: service_started
    ports:
      - "4000:4000"
    networks:
      - ev_net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: npm run start:prod

  ev_registry:
    build: ./ev_registry
    container_name: ev_registry
    environment:
      DB_HOST: "db"
      DB_PORT: 5432
      DB_NAME: "evcharging"
      DB_USER: "usuario"
      DB_PASSWORD: "contraseña"
      PORT: 4001

    volumes:
      - ./certs/registry.crt:/certs/registry.crt
      - ./certs/registry.key:/certs/registry.key
    depends_on:
      db: 
        condition: service_started
    ports:
      - "4001:4001"
    networks:
      - ev_net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4001"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: npm run start:prod

  # ----------------------- FRONTEND -----------------------
  frontend:
    build: ./front/frontend-app
    container_name: ev_frontend
    ports:
      - "8862:80"
    networks:
      - ev_net
    restart: on-failure

  # weather_control
  # include API and ports
  
  # ----------------------- KAFKA -----------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: ev_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ev_net

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: ev_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 10s
      timeout: 5s
      retries: 10

    ports:
      - "9092:9092"
    networks:
      - ev_net
  # ----------------------- CHARGING POINTS -----------------------
  cp_pair:
    build:
      context: ./charging_point/cp
      dockerfile: Dockerfile
    environment:
      KAFKA_BROKER: "kafka:9092"
      CENTRAL_HOST: "https://ev_central:4000"
      REGISTRY_GRAPHQL: "https://ev_registry:4001/graphql"
      ENGINE_PORT: "7000"
      ENGINE_HOST: "0.0.0.0"
      MONITOR_PORT: "9000"
      CP_INDEX: "${HOSTNAME}"
    volumes:
      - ./certs/central.crt:/certs/central.crt
      - ./certs/registry.crt:/certs/registry.crt
    depends_on:
      kafka:
        condition: service_healthy
      ev_central:
        condition: service_healthy
      ev_registry:
        condition: service_healthy
    ports:
      - "9100-9199:9000"
    networks: [ev_net]
    restart: on-failure

  # ----------------------- DRIVERS -----------------------
  driver:
    build:
      context: ./driver
      dockerfile: Dockerfile
    environment:
      KAFKA_BOOTSTRAP: "kafka:9092"
      FLASK_PORT: "5000"
    depends_on:
      kafka:
        condition: service_healthy
      ev_central:
        condition: service_started
    # UI del driver expuesta por réplica en rango 9200-9299
    ports:
      - "9200-9299:5000"
    networks: [ev_net]
    restart: on-failure

  # ----------------------- VOLUMES & NETWORKS -----------------------
volumes:
  postgres_data:
  
  kafka_data:

networks:
  ev_net:
    driver: bridge