FROM python:3.11-slim

WORKDIR /app

COPY . /app

RUN pip install flask flask-socketio eventlet

RUN apt-get update \
 && apt-get install -y dos2unix \
 && dos2unix /app/start_cp.sh \
 && chmod +x /app/start_cp.sh \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

CMD ["/app/start_cp.sh"]