FROM python:3.11-slim

WORKDIR /app

COPY dummy_central.py .
COPY requirements.txt .

# Instala dependencias comunes (Flask + Kafka)
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 4000

CMD ["python", "dummy_central.py"]
